#!/bin/bash
# Tests for `ceo trace` — covers cmd_trace's input validation, registry-parse
# error path, missing-claude diagnostic, unregistered-name warning, and the
# load-bearing `unset CEO_PLAYBOOK_ID` inside the subshell.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CEO_BIN="$SCRIPT_DIR/ceo"

# shellcheck source=test-harness.sh
source "$SCRIPT_DIR/test-harness.sh"

setup() {
  TEST_HOME=$(mktemp -d)
  HOME_BACKUP="$HOME"
  PATH_BACKUP="$PATH"
  export HOME="$TEST_HOME"
  mkdir -p "$TEST_HOME/bin" "$TEST_HOME/vault/CEO" "$TEST_HOME/.ceo"
  # The generated registry is host-local now ($HOME/.ceo/registry.json), not in
  # the synced vault — `ceo trace` reads it from there.
  REGISTRY_FILE="$HOME/.ceo/registry.json"

  export VAULT="$TEST_HOME/vault"
  export CEO_VAULT="$VAULT"
  export CEO_DIR="$VAULT/CEO"

  # Stubbed claude records argv + CEO_PLAYBOOK_ID + stdin to disk so tests
  # can assert what the subshell handed it.
  cat > "$TEST_HOME/bin/claude" << SH
#!/bin/bash
printf '%s' "\${CEO_PLAYBOOK_ID:-EMPTY}" > "$TEST_HOME/claude-saw-playbook-id.txt"
printf '%s\n' "\$@" > "$TEST_HOME/claude-argv.txt"
cat > "$TEST_HOME/claude-stdin.txt"
echo "stub-claude-out"
SH
  chmod +x "$TEST_HOME/bin/claude"

  export PATH="$TEST_HOME/bin:$PATH_BACKUP"
}

teardown() {
  rm -rf "$TEST_HOME"
  export HOME="$HOME_BACKUP"
  export PATH="$PATH_BACKUP"
  unset VAULT CEO_VAULT CEO_DIR
}

# Runs cmd_trace in a subshell with the function extracted from scripts/ceo
# and the supporting stubs (ceo_validate_vault, vault binding) inlined. Args
# are passed via positional parameters to avoid bash -c parsing surprises
# when test inputs contain shell metacharacters.
_run_cmd_trace() {
  local body
  body=$(sed -n '/^cmd_trace()/,/^}$/p' "$CEO_BIN")
  bash -c '
    set -uo pipefail
    VAULT="$1"; CEO_VAULT="$2"; CEO_DIR="$3"; REGISTRY_FILE="$4"
    shift 4
    ceo_validate_vault() { return 0; }
    _ceo_registry_path() { printf "%s\n" "$REGISTRY_FILE"; }
    '"$body"'
    cmd_trace "$@"
  ' -- "$VAULT" "$CEO_VAULT" "$CEO_DIR" "$REGISTRY_FILE" "$@" 2>"$TEST_HOME/err" 1>"$TEST_HOME/out"
}

test_cmd_trace_missing_name_prints_usage_and_exits_1() {
  local rc=0
  _run_cmd_trace || rc=$?
  assert_eq "$rc" "1" "missing name must exit 1"
  assert_contains "$(cat "$TEST_HOME/out")" "Usage: ceo trace" "must print usage"
}

test_cmd_trace_rejects_invalid_name_with_shell_metachars() {
  local rc=0
  _run_cmd_trace "evil';rm" || rc=$?
  assert_eq "$rc" "1" "names with shell metacharacters must be rejected"
  assert_contains "$(cat "$TEST_HOME/err")" "invalid playbook name" "stderr must explain rejection"
}

test_cmd_trace_rejects_pure_dot_name() {
  local rc=0
  _run_cmd_trace ".." || rc=$?
  assert_eq "$rc" "1" "'..' must be rejected to prevent path-traversal in registry/metadata"
}

test_cmd_trace_rejects_leading_dot_name() {
  local rc=0
  _run_cmd_trace ".hidden" || rc=$?
  assert_eq "$rc" "1" "names starting with '.' must be rejected"
}

test_cmd_trace_rejects_unknown_arg_to_stderr() {
  local rc=0
  _run_cmd_trace morning-scan --bogus || rc=$?
  assert_eq "$rc" "1" "unknown args must exit 1"
  assert_contains "$(cat "$TEST_HOME/err")" "Unknown arg" "rejection must go to stderr"
}

test_cmd_trace_rejects_non_numeric_limit() {
  local rc=0
  _run_cmd_trace morning-scan --limit abc || rc=$?
  assert_eq "$rc" "1" "non-numeric --limit must exit 1"
  assert_contains "$(cat "$TEST_HOME/err")" "--limit must be a positive integer" "must surface the constraint"
}

test_cmd_trace_rejects_non_numeric_limit_equals_form() {
  local rc=0
  _run_cmd_trace morning-scan --limit=zero || rc=$?
  assert_eq "$rc" "1" "non-numeric --limit=NNN must exit 1"
}

test_cmd_trace_missing_claude_binary_exits_with_diagnostic() {
  local rc=0
  PATH=/usr/bin:/bin _run_cmd_trace morning-scan || rc=$?
  assert_eq "$rc" "1" "missing claude binary must exit 1"
  assert_contains "$(cat "$TEST_HOME/err")" "'claude' CLI not found" "diagnostic must name the missing binary"
}

test_cmd_trace_warns_when_playbook_not_registered() {
  cat > "$REGISTRY_FILE" << 'JSON'
{ "playbooks": [ { "name": "other-playbook" } ] }
JSON
  _run_cmd_trace morning-scan
  assert_contains "$(cat "$TEST_HOME/err")" "is not in" "must warn when name is missing from registry"
  assert_file_exists "$TEST_HOME/claude-argv.txt" "claude must still be invoked (warning, not abort)"
}

test_cmd_trace_aborts_on_malformed_registry() {
  echo "this is not json {{{" > "$REGISTRY_FILE"
  local rc=0
  _run_cmd_trace morning-scan || rc=$?
  assert_eq "$rc" "1" "malformed registry.json must abort, not be reported as 'not registered'"
  assert_contains "$(cat "$TEST_HOME/err")" "not valid JSON" "diagnostic must distinguish parse failure from miss"
}

test_cmd_trace_unsets_ceo_playbook_id_before_calling_claude() {
  # Caller has its own playbook_id; the trace query itself must not inherit it,
  # otherwise observations generated by the trace would be self-tagged.
  CEO_PLAYBOOK_ID=outer-playbook _run_cmd_trace morning-scan
  assert_file_exists "$TEST_HOME/claude-saw-playbook-id.txt" "claude must have been invoked"
  local got
  got=$(cat "$TEST_HOME/claude-saw-playbook-id.txt" 2>/dev/null || echo "MISSING")
  assert_eq "$got" "EMPTY" "cmd_trace must unset CEO_PLAYBOOK_ID before invoking claude"
}

test_cmd_trace_passes_allowed_tools_to_claude() {
  _run_cmd_trace morning-scan
  local argv
  argv=$(cat "$TEST_HOME/claude-argv.txt" 2>/dev/null || echo "")
  assert_contains "$argv" "--allowed-tools" "must restrict claude to a specific tool set"
  assert_contains "$argv" "mcp__claude-mem__observation_search" "must allow observation_search"
}

run_tests
